Solution for operators, matching and functions/Authentication
jusual/scala-school pull request #2
Opened 2017-03-19 21:43 UTC by jusual

2017-03-19 22:11 UTC, vatt2001 requested changes

2017-03-19 22:11 UTC, vatt2001 commented on src/main/scala/lectures/functions/Computations.scala
> +    dataArray => dataArray.filter(dataItem => filterArray.contains(dataItem))
Последний `sleep` оказался вне возвращаемой функции, хотя он неразрывно с ней связан (эмулирует задежрку выполнения `dataArray.filter`.

2017-03-19 22:11 UTC, vatt2001 commented on src/main/scala/lectures/matching/SortingStuff.scala
> +      case boots@Boots(_, _) => stuffBox.copy(boots = boots :: stuffBox.boots)
Здесь и выше нас интересуют не любые часы/книги/ботинки, а только определенные, см. условие задания

2017-03-20 07:45 UTC, sergeypopov83 commented on src/main/scala/lectures/functions/Computations.scala
> +  def filterApplied = functionalComputation(filterData)
А если бы это был val то разница в производительности была бы очень заметна. 
Что бы избавиться от NPE убери extends App из описания классов и верни сюда val.
После того как это сделаешь, напиши, пожалуйста, почему, как ты думаешь, изменились показатели производительности

2017-03-20 07:52 UTC, sergeypopov83 commented on src/main/scala/lectures/matching/SortingStuff.scala
> +      case book@Book(_, isInteresting) if isInteresting => stuffBox.copy(books = book :: stuffBox.books)
В Мэтчинг можно подставлять конкретные значения иногода это удобно
Например в для книг можно написать вот так ..
case book@Book(_, true) => stuffBox.copy(books = book :: stuffBox.books)

2017-03-22 21:13 UTC, vatt2001 approved these changes

2017-03-22 21:13 UTC, vatt2001 commented
ПР мержу, но за тобой еще объяснение результатов сравнения производительности разных computation-ов

2017-03-22 21:14 UTC, merged